@startuml
autonumber
actor Client
box "Bronhouder" #LightBlue
actor Practitioner_Alice
participant Registrator_XIS
participant Extractor
participant Convertor
database Resource_Server
participant Knooppunt_Bron
end box

box "Nictiz/National" #LightPink
database mapping_inforequest_to_searchurls
database authz_role_to_searchurl
end box

box "Afnemer"
participant Knooppunt_Afn
participant Translator
participant Query_Builder
participant Viewer
participant Requestor_XIS
actor Practitioner_Bob
end box

group PUBLICEREN
  Practitioner_Alice -> Registrator_XIS : log in
  group register data and make data interoperable and accessible
    Practitioner_Alice -> Registrator_XIS : register healthcare data
    Registrator_XIS <- Extractor: pull healthcare data
    Extractor -> Convertor: deliver healthcare data
    Convertor -> Convertor : convert to FHIR
    Convertor -> Resource_Server : POST FHIR data
  end

  group make data findable
    Practitioner_Alice -> Registrator_XIS : register specific consent
    group Authorization registration
      Registrator_XIS -> Knooppunt_Bron : register authorization
      Registrator_XIS <- Knooppunt_Bron : ok
      Knooppunt_Bron -> Knooppunt_Afn : sync authorizations
    end
  end
end

group RAADPLEGEN
  group user authentication
    Practitioner_Bob -> Requestor_XIS : inloggen
    Requestor_XIS -> Viewer: SSO\n <<BSN,\nuser_id>>
    Viewer -> Knooppunt_Afn : user authentication
    Knooppunt_Afn -> Viewer : authentication challenge
    Viewer -> Practitioner_Bob : Show QR-code
    Practitioner_Bob -> Knooppunt_Afn: sign authentication
    Knooppunt_Afn -> Viewer : <<authn-contract>>
  end
  Viewer -> Query_Builder : information request\n<<BSN,\nauthn-contract>>
  
  group endpoint localisation and authorization
    Query_Builder -> Knooppunt_Afn : find FHIR endpoints
    Query_Builder <- Knooppunt_Afn : <<FHIR endpoints>>
    
    loop FOR EACH Bron
    Query_Builder -> Knooppunt_Afn : request access_token
    Knooppunt_Afn -> Knooppunt_Bron : request access token\n<<JWT-grant>>
    Knooppunt_Afn <- Knooppunt_Bron: access token
    Query_Builder <- Knooppunt_Afn : access token
    end
  end 

  Query_Builder ->  mapping_inforequest_to_searchurls : get search-urls <<info request>>
  Query_Builder <-  mapping_inforequest_to_searchurls : <<search-urls>>
  
  loop FOR EACH Bron
    loop FOR EACH search url
      Query_Builder -> Resource_Server : request FHIR-resource\n<<access token>>
      Resource_Server -> Knooppunt_Bron: validate token
      Resource_Server <- Knooppunt_Bron: ok
      Query_Builder <- Resource_Server : FHIR resource
    end
    Query_Builder -> Translator: request translation\nof FHIR/SNOMED
    Query_Builder <- Translator: translated resources
    Query_Builder --> Viewer: translated resources
  end
  Viewer -> Viewer : generate view
  Viewer -> Practitioner_Bob: present view
  Practitioner_Bob -> Practitioner_Bob: enjoy view!
end
@enduml
