@startuml
autonumber 1.1.1
participant Menzis_ZK1 as ZK1
participant LUA_runner as LUA
participant Authz_service as authz
participant filter as filter
participant proxy_ciz as proxy
participant CIZ as ciz
group authz & access token flow
  ZK1 -> LUA : authz token request\n(without consent)\n
  LUA -> LUA : generate scope/\naccess model
  LUA -> authz : authz code request
  authz -> ZK1 : <authz code>
  ZK1 -> authz : request access token (JWT)\n<authz code>
  ZK1 <-- authz : <access token>
end
autonumber inc b
ZK1 -> filter : post gql mutation \nsubscription-request <access token>
filter -> filter: apply \naccess policy
filter -> proxy : post gql mutation
proxy -> ciz : post gql mutation
ciz --> ZK1 : <abonnement id>
@enduml
